const {extractCategoriesAndOptions, generateCheckBoxes, showBoxSelector, checkedValuesObjectGenerator, verifyCheckedBoxes, mergeVerifyCheckedBoxes, removeChecksExceptCurrent, onlyOne, onlyOneEnforcer, allOK, checkBoxVerificationSystem, dragElement, multiCheck, singleCheck, targetCheck, simulateSelection, pickMultiClassClassifiers, verifyAllClassifiersChecked } = require("./checkBoxSelectors.js")
const {filterDataByCheckBox, _filterNull, _removeNullColumns, nullsOut, onlyUnique, separateDataInGroups} = require('./dataProcessUtils.js')
const {documentAppender, renderGraphBoxes, generatePieChartsContainers, initiateDashboard} = require('./generateHTMLstructure.js')
const {_randomNoRepeats, colorGenerator, _convertToOpacity, _dataGenerator, graphCustom, graphCustomPie, singleLabelExtractor, displayNonGraphs, shortenLabel, wrapGraph, nextDependent } = require('./graphFunctions.js')
const { styleGen, loadArea, showUnderliningMap, drawMap } = require('./leafLetFunctions.js')
const { sankeyControls, verifySankeyOrder, connectionGenerator } = require('./sankeyFunctions.js')
const { copyText, shareDashboard, checkBoxesFromUrl, hideSelectors } = require('./shareFunctions.js')

module.exports = { extractCategoriesAndOptions, generateCheckBoxes, showBoxSelector, checkedValuesObjectGenerator, verifyCheckedBoxes, mergeVerifyCheckedBoxes, removeChecksExceptCurrent, onlyOne, onlyOneEnforcer, allOK, checkBoxVerificationSystem, dragElement, multiCheck, singleCheck, targetCheck, simulateSelection, pickMultiClassClassifiers, verifyAllClassifiersChecked, filterDataByCheckBox, _filterNull, _removeNullColumns, nullsOut, onlyUnique, separateDataInGroups, documentAppender, renderGraphBoxes, generatePieChartsContainers, initiateDashboard, _randomNoRepeats, colorGenerator, _convertToOpacity, _dataGenerator, graphCustom, graphCustomPie, singleLabelExtractor, displayNonGraphs, shortenLabel, wrapGraph, nextDependent, styleGen, loadArea, showUnderliningMap, drawMap, sankeyControls, verifySankeyOrder, connectionGenerator, copyText, shareDashboard, checkBoxesFromUrl, hideSelectors }
